### ISSUE TITLE
Add Bower support

### ISSUE THREAD

**Issue by daFish** [ninsuo/symfony2-collection#1]
It would be great if this plugin could be installable using [Bower](http://bower.io/).

**Comment by ninsuo** [comment]
Thank you for the suggestion.

I don't know about Bower, but I'll take care about your issue when the plugin will be stable.

Alain

**Comment by daFish** [comment]
Thanks, Alain.

**Comment by ninsuo** [comment]
Added Bower support in https://github.com/ninsuo/symfony2-collection/commit/72582c4bbf5ac9f7453fa4584d930dac59f28ed8 

Thank you daFish!
Alain
